apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: jira-create-issue
description: "Create a new Jira issue with specified fields"
inputs:
  jira-url:
    description: "Jira instance URL (e.g., https://your-domain.atlassian.net)"
    required: true
  jira-username:
    description: "Jira username or email address"
    required: true
  jira-token:
    description: "Jira API token"
    required: true
  project-key:
    description: "Project key where the issue will be created (e.g., MYPROJECT)"
    required: true
  issue-type:
    description: "Issue type name (e.g., Bug, Story, Task, Epic)"
    required: true
  issue-fields:
    description: "YAML object containing issue fields (will be converted to JSON for API)"
    required: true
  notify-users:
    description: "Whether to send notifications to users about the new issue"
    default: "true"
    required: false
  dry-run:
    description: "If true, validates the issue data without creating it"
    default: "false"
    required: false

outputs:
  issue-key:
    value: ${{ steps.create-issue.outputs.issue-key }}
    description: "The key of the created issue (e.g., PROJ-123)"
  issue-id:
    value: ${{ steps.create-issue.outputs.issue-id }}
    description: "The internal ID of the created issue"
  issue-url:
    value: ${{ steps.create-issue.outputs.issue-url }}
    description: "The URL to view the created issue"

runs:
  using: composite
  steps:
    - id: create-issue
      name: Create Jira Issue
      uses: docker://cloudbeesdemo/jira-actions:v2
      shell: sh
      run: |
        /app/jira-actions create-issue \
          --url "${{ inputs.jira-url }}" \
          --username "${{ inputs.jira-username }}" \
          --token "${{ inputs.jira-token }}" \
          --project "${{ inputs.project-key }}" \
          --type "${{ inputs.issue-type }}" \
          --issue-fields '${{ inputs.issue-fields }}' \
          ${{ inputs.dry-run == 'true' && '--dry-run' || '' }} \
          ${{ inputs.notify-users == 'false' && '--notify-users=false' || '' }} \
          --verbose
